apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-webuni.fullname" . }}
  labels:
    {{- include "spring-webuni.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spring-webuni.selectorLabels" . | nindent 4 }}
